version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always

  producer:
    build:
      context: ./src/producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - INPUT_TOPIC=interaction

  pyspark_consumer:
    build:
      context: ./src/pyspark_consumer
      dockerfile: Dockerfile
    container_name: pyspark_consumer
    depends_on:
      - broker
      - producer
      - cassandra
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - INPUT_TOPIC=interaction
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - CASSANDRA_HOST=cassandra  # Use service name 'cassandra' here
      - CASSANDRA_KEYSPACE=interaction_data
      - CASSANDRA_TABLE=interaction_data

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL (Cassandra Query Language) port
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_LISTENER_TRANSPORT_PORT=7000
      - CASSANDRA_CQL_PORT=9042
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra/init:/docker-entrypoint-initdb.d  # Mount the init directory
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - cassandra
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    restart: always

volumes:
  mongo_data:
  cassandra_data:

networks:
  kafka-network:
    driver: bridge
