{
 "title": "Interaction",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "interaction_data of user ",
   "type": "xychart",
   "description": "SELECT timestamp,   user_id,   interaction_type,   COUNT(*) AS interaction_count FROM interaction_data.interaction_data GROUP BY user_id;",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "SELECT timestamp,   user_id,   interaction_type,   COUNT(*) AS interaction_count FROM interaction_data.interaction_data GROUP BY user_id;"
    }
   ]
  },
  {
   "title": "item_aggregates",
   "type": "piechart",
   "description": "select * from interaction_data.item_aggregates",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select * from interaction_data.item_aggregates"
    }
   ]
  },
  {
   "title": "user_aggregates",
   "type": "barchart",
   "description": "select * from interaction_data.user_aggregates",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "select * from interaction_data.user_aggregates"
    }
   ]
  }
 ]
}